import type { NextPage } from "next";
import Head from "next/head";
import Card from "../components/Card";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout header={<Header />} footer={<Footer />}>
        <div className={styles.grid}>
          <Card
            uri={"https://nextjs.org/docs"}
            title="Documentation"
            description="Find in-depth information about Next.js features and API."
          />
        </div>
      </Layout>
    </div>
  );
};

export default Home;
